default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

#development:
#  <<: *default
#  adapter: postgresql
#  encoding: unicode
#  host: db
#  username: postgres
#  password:
#  database: sample_rails_app_db

test:
  <<: *default
  adapter: sqlite3
  database: db/test.sqlite3

#test:
#  <<: *default
#  adapter: postgresql
#  encoding: unicode
#  host: db
#  username: postgres
#  password:
#  database: sample_rails_app_db_test

production:
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] %>
  port: 5432
